services:
    keycloak:
        image: quay.io/keycloak/keycloak:24.0.2
        command: start-dev
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=adminpassword
            - KC_HOSTNAME=localhost
            - KC_HTTP_PORT=8080
        ports:
            - '8083:8080'
        restart: unless-stopped

    mongo:
        image: mongo:7.0
        container_name: mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db

    # mysql and phpmyadmin services removed per requirement

    backend:
        build:
            context: ./backend
        volumes:
            - ./backend:/app
        working_dir: /app
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        ports:
            - '8000:8000'
        environment:
            - MONGODB_URL=mongodb://root:password@mongo:27017/
            - MONGODB_URI=mongodb://root:password@mongo:27017/?authSource=admin
            - DATABASE_NAME=add_rec_tool
        depends_on:
            - keycloak
            - mongo

    frontend:
        build:
            context: ./frontend
        ports:
            - '5173:5173'
        restart: unless-stopped
        depends_on:
            - backend

volumes:
    mongo_data:
